version: '3'
services:
  app:
    build: .
    image: jms1989/proftpdserver
    environment:
      FTP_LIST: "novapatch:M74ss4RilS4Y5"
    ports:
      - "2021:21"
    volumes:
      - ./beta-patch:/data
      - ./proftpd.conf:/etc/proftpd/proftpd.conf
    networks:
      - dokploy-network
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./beta-patch:/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.beta-patch.rule=Host(`patch.novasaga.xyz`)
      - traefik.http.routers.beta-patch.entrypoints=web
      - traefik.http.services.beta-patch.loadbalancer.server.port=80
volumes:
  beta-patch:
  
networks:
  dokploy-network:
    external: true